#!/usr/bin/env bash

# ========================
# Script: analysis
# Author: Danyan Chen
# Student id : 24063952
# Description:
#   
# ========================


# ---------- Get parameters & Validate parameters -------------
file_path=$1

if test $# -ne 1  
then 
    echo "Error: Expected 1 argument, but got $#, usage: ./anlysis <file_path>" >&2
    exit 1
fi


if test ! -s "$file_path"
then
    echo "Error: The specified input file '$file_path' does not exist or is empty." >&2
    exit 1
fi

# ---------- Q1 The most popular game mechanics is Hand Management found in xx games -------------
gawk '
function find_max(array) 
{
        max_val = 0
        for (k in array) {
            if (array[k] > max_val) {
                max_val = array[k]
                max_key = k
            }
        }
        return max_key "&&" max_val
}

BEGIN{
    FS ="\t"
}

{
    # Incase some empty field with multiple space
    # $13 is the column mechanics
    clean_mechanic = $13
    gsub(/[ \t\r\n]+/, "", clean_mechanic)

    
    # skip header and skip the empty field
    if(NR>1 && clean_mechanic !=""){

        # split(string, array, separator)
        split($13, row_values, "," )

        for(i=1;i<=length(row_values);i++){

            # Replace the possible space with ""
            gsub(/^ +| +$/,"",row_values[i])
            mechanic_count[row_values[i]]++
        }

    }


    # Incase some empty field with multiple space
    # $14 is the column domains
    clean_domain = $14
    gsub(/[ \t\r\n]+/, "", clean_domain)

    
    # skip header and skip the empty field
    if(NR>1 && clean_domain !=""){

        # split(string, array, separator)
        split($14, row_values, "," )

        for(i=1;i<=length(row_values);i++){

            # Replace the possible space with ""
            gsub(/^ +| +$/,"",row_values[i])
            domain_count[row_values[i]]++
        }

    }

}

END{
    split(find_max(mechanic_count), mparts, "&&")
    split(find_max(domain_count), dparts, "&&")
    print "The most popular game mechanics is", mparts[1], "found in", mparts[2], "games"
    print "The most style of game is", dparts[1], "found in", dparts[2], "games"
}
' "$file_path"