#!/usr/bin/env bash

# ========================
# Script: empty_cells
# Author: Danyan Chen
# Student id : 24063952
# Description:
#   This script takes a txt file as input and count the empty cells from it.
# ========================


# ---------- Get parameters & Validate parameters -------------
file_path=$1

if test $# -ne 1  
then 
    echo "Error: Expected 1 argument, but got $#, usage: ./empty_cells <file_path>" >&2
    exit 1
fi


if test ! -s "$file_path"
then
    echo "Error: The specified input file '$file_path' does not exist or is empty." >&2
    exit 1
fi

# ----------  Process file with gawk ----------

gawk '

BEGIN {
    FS=";"
}

# Store column names from the first row
NR ==1 {
    for (i=1; i<=NF; i++){
        # Store the column names in the column array
        column[i] = $i
    }

    # Only read the first line
    next
}

{for (i =1; i <=NF; i++){
        cell = $i
        gsub(/[ \t]/, "", $i)    
        if (cell == ""){
            # If the cell is empty, increment the count for that column
            count[i]++
        }
    }
}

END{
    for (i=1; i <= length(column); i++){
        # Print the column name and the count of empty cells
        # "+0" is used to prevent some columns no empty cells from printing ""
        printf ("%s: %d\n", column[i], count[i]+0)
    }

}
' "$file_path"