#!/usr/bin/env bash

# ========================
# Script: empty_cells
# Author: Danyan Chen
# Student id : 24063952
# Description:
# This script cleans the input file and writes the result to standard output.
# It replaces semicolons with tabs, normalizes line endings, 
# fixes decimal formats, removes non-ASCII characters, and fills missing IDs
# ========================


# ---------- Get parameters & Validate parameters -------------
file_path=$1

if test $# -ne 1  
then 
    echo "Error: Expected 1 argument, but got $#, usage: ./preprocess <file_path>" >&2
    exit 1
fi

if ! echo "$file_path" | grep -q '\.txt$'
then
    echo "Error: The specified input file '$file_path' is not a CSV file." >&2
    exit 1
fi

if test ! -s "$file_path"
then
    echo "Error: The specified input file '$file_path' does not exist or is empty." >&2
    exit 1
fi


# ---------- Convert the ";" separator to the  <tab> character "\t" -------------
gawk '

{ 
# Convert the ";" separator to the  <tab> character "\t"
gsub(/;/,"\t")

# Convert the Microsoft line endings to Unix line endings
for(i=1;i<=NF;i++)
{
    if ($i ~ /^[0-9][0-9]*,[0-9][0-9]*$/)
    {
        gsub(/,/,".",$i)
    }
}
print
}

' "$file_path"
